import { Schema } from "effect";

// CONSISTENCY-FIX TYPE-02: ProductStatus now lives in @repo/common — removed
// inline duplicate definition.
import type { ProductStatus } from "@repo/common";

export type { ProductStatus };

// ── Admin-specific product type ────────────────────────────────────────────
// NOTE(TYPE-03): diverges from @repo/common/Product intentionally —
//   • admin Product has status: ProductStatus (ACTIVE|DRAFT|ARCHIVED)
//   • common Product has isActive + slug + categoryId (web-facing fields)
// Reconcile with product-service team before merging these types.
export type Product = {
  id: string;
  name: string;
  price: number;
  stock: number;
  sku: string;
  status: ProductStatus;
  description: string | undefined;
  imageUrls: string[] | undefined;
  createdAt: string | undefined;
  updatedAt: string | undefined;
};

// NOTE(TYPE-03): admin NewProduct omits slug (auto-generated by backend).
// @repo/common NewProduct requires slug — needs API contract review.
export type NewProduct = {
  name: string;
  price: number;
  stock: number;
  sku: string;
  description?: string;
  imageUrls?: string[];
  status?: ProductStatus;
};

// NOTE(TYPE-03): role is string (not UserRole) to handle OWNER + FINANCE roles
// that the web-facing @repo/common/UserRole doesn't include yet.
// Fixed in @repo/common UserRole — migrate to import type { User } after
// confirming all consumers handle the broader union.
export type User = {
  id: string;
  name: string;
  email: string;
  role: string;
  createdAt: string | undefined;
};

// ── Re-exported API response types ────────────────────────────────────────
// TYPE-04: definisi kanonik ada di src/types/api-responses.ts — tidak lagi
// bergantung pada layer client (lib/api.ts). Dipendenza inversa eliminata.
export type {
  AuditLogEntry,
  DashboardStats,
  OrderDetail,
  OrderSummary,
} from "@/types";

// ── Effect.Schema — request / response validation ─────────────────────────

export const ProductSchema = Schema.Struct({
  id: Schema.String,
  name: Schema.String,
  price: Schema.Number,
  stock: Schema.Number,
  sku: Schema.String,
  status: Schema.Literal("ACTIVE", "DRAFT", "ARCHIVED"),
  description: Schema.optional(Schema.String),
  imageUrls: Schema.optional(Schema.Array(Schema.String)),
  createdAt: Schema.optional(Schema.String),
  updatedAt: Schema.optional(Schema.String),
});
export type ProductDecoded = Schema.Schema.Type<typeof ProductSchema>;

export const ProductListSchema = Schema.Struct({
  items: Schema.Array(ProductSchema),
  total: Schema.Number,
});

export const NewProductSchema = Schema.Struct({
  name: Schema.String.pipe(Schema.minLength(1)),
  price: Schema.Number.pipe(
    Schema.filter((n) => n > 0, { message: () => "price must be positive" })
  ),
  stock: Schema.Number.pipe(
    Schema.filter((n) => n >= 0, {
      message: () => "stock must be non-negative",
    })
  ),
  sku: Schema.String.pipe(Schema.minLength(1)),
  description: Schema.optional(Schema.String),
  imageUrls: Schema.optional(Schema.Array(Schema.String)),
  status: Schema.optional(Schema.Literal("ACTIVE", "DRAFT", "ARCHIVED")),
});
export type NewProductInput = Schema.Schema.Type<typeof NewProductSchema>;

export const UpdateProductSchema = Schema.partial(NewProductSchema);
export type UpdateProductInput = Schema.Schema.Type<typeof UpdateProductSchema>;
